minimal changes
fabricjs/fabric.js pull request #7916
Opened 2022-04-30 23:22 UTC by asturur

This PR rename canEnter in canEnterGroup and move canEnterGroup to an higher level of the logic so that it can stops adding not supported objects to groups.

2022-04-30 23:35 UTC, asturur commented
replace #7900 
@ShaMan123 have a look at this solution to catching the issue before need to throw

2022-05-01 04:35 UTC, ShaMan123 approved these changes
This is much better no doubt.

However:

> The advantage of moving it to add/insertAt is clear. That's how it should be. The disadvantage is a drop in perf for large groups because we add an iteration over objects. Unless we manage to change collection logic to run all logic on object in one single iteration

_Originally posted by @ShaMan123 in https://github.com/fabricjs/fabric.js/pull/7900#discussion_r862421564_

But I think we should move forward

2022-05-01 04:36 UTC, ShaMan123 commented
> Background color has been left in for group since the layers in group concept may be slow to enter fabricjs.

Could you explain why Layer will take time to merge into master?
I am fine with dropping background. I have worked around it in my projects.

2022-05-01 04:38 UTC, ShaMan123 requested changes
Please push this
https://github.com/fabricjs/fabric.js/pull/7900/files#diff-216444c1bc3837d560c8241c4d9643b6de8c147095081c5b38715b9e058c24cbR587

2022-05-01 10:48 UTC, asturur commented
> > Background color has been left in for group since the layers in group concept may be slow to enter fabricjs.
> 
> Could you explain why Layer will take time to merge into master? I am fine with dropping background. I have worked around it in my projects.

Because i have seen the PR, and i don't like the idea of having special logic to allow layers to react to both canvas and group  container. I want to simplify things not make more complicated. The layer per se is ok, a dimensionless group always interactive. fine.
the gymmics in the layout management less.
But we can talk there, or maybe we could make an hands on and see how we can make it simpler.

2022-05-01 10:51 UTC, asturur commented
The only large group i know of is the spray brush, can you think of others?
maybe the spray brush shouldn't be a group with thons of rect or circles, it should be just a function able to render a spray effect.

2022-05-01 14:16 UTC, ShaMan123 commented
I guess you are right. I don't use huge groups in my projects.

2022-05-02 08:48 UTC, ShaMan123 commented
This next? Don't forget my review

2022-06-10 15:31 UTC, asturur commented
Applied fixes and merging

2022-06-10 15:32 UTC, merged

2022-06-10 15:47 UTC, ShaMan123 reviewed
What about `insertAt` - we should filter that as well

2022-06-10 15:47 UTC, ShaMan123 commented on src/shapes/group.class.js
> +        console.error('fabric.Group: trying to add group to itself, this call has no effect');
so we should only warn now, right?