add a undo_redo lib
fabricjs/fabric.js pull request #8073
Opened 2022-07-20 09:33 UTC by QJesus

1. fabric.Text.text cannot be null\undefined
2. undo_redo extension

2022-07-22 15:45 UTC, ShaMan123 commented
> fabric.Text.text cannot be null\undefined

Can be a standalone PR

2022-07-23 03:29 UTC, melchiar commented on lib/undo_redo.js
> +    fabric.canvas.prototype.__setupCanvas = function (serialized, enlivenedObjects, renderOnAddRemove, callback) {
```suggestion
    const ___setupCanvas = fabric.Canvas.prototype.__setupCanvas;
    fabric.Canvas.prototype.__setupCanvas = function (serialized, enlivenedObjects, renderOnAddRemove, callback) {
```

Nice lib idea! `fabric.canvas` should have uppercase C though

2022-07-23 03:35 UTC, melchiar requested changes
Can we improve some of these variable names. Names like t, v, and h aren't very human readable.

2022-07-23 07:15 UTC, ShaMan123 commented
I don't think history should be part of core.
IMO history is something that is heavily customized between different apps.
If it is hard to build such functionality I would suggest PRing to make fabric easier to develop such functionalities. That makes sense to me.
Regardless, `saveObjectTransform` isn't good enough. What about skewing? cacheProperties? stateProperties?
This re-introduces state management which we have decided to deprecate in #7920

2022-07-23 07:18 UTC, ShaMan123 commented
@QJesus I am very for contributions, hope I didn't put you down.
We are migrating to TS if you want to join the effort. And that should eventually open up a better way to write extensions for fabric.

2022-07-25 20:27 UTC, asturur commented
Actually we wanted to think about a more simple way to tackle this, both on core and an external lib. We have to move forward with our schedule and as soon as the rollup pr is merged, we can get back to this.

2022-07-26 02:23 UTC, melchiar commented
@QJesus Thanks for the pr, however as asturur explained this isn't quite the direction we want to take with an undoredo library. I'm going to close this PR for now, but we can revisit adding an official undoredo component once v6 is out of the gate.

2022-07-26 02:23 UTC, closed without merging