Convert circle.class.ts to Typescript
fabricjs/fabric.js pull request #8117
Opened 2022-08-04 07:27 UTC by avra-m3

2022-08-04 08:40 UTC, asturur commented
Hi @avra-m3  you are having the issue we are all having.
87 tests in the browser fail.
We are looking in what we did wrong.

2022-08-04 08:44 UTC, avra-m3 commented
No worries, I figured it wasn't related to this pr - is the code style one also meant to be failing?

2022-08-04 11:01 UTC, asturur commented
@avra-m3 there are 2 things to take in account.
1. types: we want to discuss internally who to actually do them ( for example yes, cacheproperties are an array of string, but we would like them to be an enum of those the possible properties )
2. things are WIP in this moment and breaks easily

https://github.com/fabricjs/fabric.js/pull/8118
This is how i converted Rect, and from contributors we are looking forwad prs of this kind.
Transform the old code in more modern es6+ code, deconstructs whatever you can find.

One of the issues i had was that i naturally used lfat arrows for one liners, but that was wrong and i didn't expect because usually i have layers of babel that fix that.

You can ask all the support you want if you want to help.

2022-08-04 11:02 UTC, asturur commented
Oh LINT is supposed to fail, but not on the main file you are working on.

2022-08-04 11:06 UTC, asturur commented
Another tip, i know this code well and i was making plain mistakes in the previous PR, and then i started this new own, and i did baby steps.

I suggest you start fresh from master, and give a look at the commits i did, do the White space commit at the end when everything pass.

2022-08-04 11:15 UTC, avra-m3 commented
Sorry, took initiative on the types thinking it would save work on a subsequent pass, happy to roll them all back, or is it mostly just the cache properties one?

2022-08-04 11:22 UTC, avra-m3 commented
I just checked your pr and either I missed some of your changes on the first pass or you made some updates - I'll fixup this pr tomorrow. Apologies.

2022-08-04 11:34 UTC, asturur commented
> Sorry, took initiative on the types thinking it would save work on a subsequent pass, happy to roll them all back, or is it mostly just the cache properties one?

In my message i mispeleed how with who.
There is not to execuse for initiative, is fine, is just that in this moment would be just more code changes. We want to have all the library converted to es6 and import/exports before start typing or refactoring or adding types.

2022-08-04 11:35 UTC, asturur commented
> I just checked your pr and either I missed some of your changes on the first pass or you made some updates - I'll fixup this pr tomorrow. Apologies.

The PR you saw was probably the one i closed in favor of this.

2022-08-04 11:38 UTC, avra-m3 commented
> > Sorry, took initiative on the types thinking it would save work on a subsequent pass, happy to roll them all back, or is it mostly just the cache properties one?
> 
> In my message i mispeleed how with who.
> There is not to execuse for initiative, is fine, is just that in this moment would be just more code changes. We want to have all the library converted to es6 and import/exports before start typing or refactoring or adding new features.

Yep easy totally understand, I'll leave it to es6 changes, I didn't get that part of the memo. I assume leave in the ts nocheck comment at the top in that case?

Thanks for the quick replies sorry for the misunderstandings.

2022-08-09 09:23 UTC, ShaMan123 commented
@avra-m3 if you need help don't hesitate to ping one of us

2022-08-09 09:25 UTC, ShaMan123 requested changes

2022-08-09 09:25 UTC, ShaMan123 commented on src/shapes/circle.class.ts
> +  const parsedAttributes = fabric.parseAttributes(element, fabric.Circle.ATTRIBUTE_NAMES);
```suggestion
  const parsedAttributes = fabric.parseAttributes(element, Circle.ATTRIBUTE_NAMES);
```

lookup all fabric.Circle and replace them

2022-08-10 00:03 UTC, avra-m3 commented
Declining and will raise a pr from new branch.

2022-08-10 00:03 UTC, closed without merging