fix(Object): Fixes centeredScaling prop type
fabricjs/fabric.js pull request #9401
Opened 2023-10-05 12:30 UTC by HesamSoleymani

## Motivation

centeredScaling type is set to "false" instead of "boolean" in v6
As @ShaMan123  mentioned in [this discussion](https://github.com/fabricjs/fabric.js/discussions/9398), it looks like a mistake...

## Description

```
  /**
   * When true, this object will use center point as the origin of transformation
   * when being scaled via the controls.
   * <b>Backwards incompatibility note:</b> This property replaces "centerTransform" (Boolean).
   * @since 1.3.4
   * @type Boolean
   * @default
   */
  centeredScaling: false;
```

## Changes

I've just changed centeredScaling type in FabricObjectProps.ts

2023-10-05 14:14 UTC, ShaMan123 reviewed
thanks, could it be that it is optional as well?

2023-10-05 14:41 UTC, HesamSoleymani commented on src/shapes/Object/types/FabricObjectProps.ts
> +  centeredScaling: boolean;
Is it necessary? I mean I think Partial<FabricObjectProps> is used everywhere so every option is optional...
If it is, then what about other props which are still not optional in FabricObjectProps ? (such as centeredRotation, selectionBackgroundColor, selectable and ...)

2023-10-05 14:47 UTC, ShaMan123 commented on src/shapes/Object/types/FabricObjectProps.ts
> +  centeredScaling: boolean;
I will give a look and follow up if needed

2023-10-05 14:48 UTC, ShaMan123 commented
Can you add a log to the changlog?
Then I can merge

2023-10-06 09:35 UTC, asturur requested changes
@HesamSoleymani please also change this here:
https://github.com/fabricjs/fabric.js/blob/master/src/shapes/Object/InteractiveObject.ts#L58
to a declare boolean

2023-10-06 10:02 UTC, HesamSoleymani commented
Everything is ok now about this pr?

2023-10-06 10:08 UTC, asturur submitted a review, later dismissed

2023-10-06 10:10 UTC, asturur commented
i think so.
@ShaMan123 wanted to have a look at something, i approved, when he has time he can check and merge or comment.

2023-10-07 00:59 UTC, ShaMan123 approved these changes

2023-10-07 01:55 UTC, merged