fix: colorPropToSVG comply with svg specification
fabricjs/fabric.js pull request #9408
Opened 2023-10-11 09:31 UTC by tyutjohn

## Motivation
@closes https://github.com/fabricjs/fabric.js/issues/9407

## Description

Change the output content of the colorPropToSVG function

## Changes
Change ':' to '='

How to write tests correctly, I need a little help, old test component seem doesn't work. This change is very small. Can anyone help me add test? I'm a little busy recently, Sorry

2023-10-12 04:58 UTC, ShaMan123 commented
I am guessing this is a regression, how didn't our tests catch this?

2023-10-12 05:02 UTC, ShaMan123 requested changes
This seems wrong to me
Looking at usages in fabric the only usage that looks wrong is 
![image](https://github.com/fabricjs/fabric.js/assets/34343793/8a6db002-85e2-46bd-bc6b-ea2014d3d856)

2023-10-12 05:03 UTC, ShaMan123 commented
and indeed that is what you reported in your issue

2023-10-12 05:04 UTC, ShaMan123 commented
I suggest refactoring the util `colorPropToSVG` to accept a third arg `separator: ':' | '='`

2023-10-12 05:11 UTC, tyutjohn commented
> refactoring

I don't know if it's necessary to add a third arg bacause I only found the function is used only here

2023-10-12 05:15 UTC, tyutjohn commented
> I suggest refactoring the util `colorPropToSVG` to accept a third arg `separator: ':' | '='`

On the old code I only found a file using it, do you want to add the default value ':' to the third parameter?

2023-10-12 05:34 UTC, ShaMan123 commented
Find all usages and add what is needed IMO, very little usage.

2023-10-12 05:56 UTC, tyutjohn commented
> I am guessing this is a regression, how didn't our tests catch this?

How to do regression testing? The old test component should not test whether the exported svg is correct.

2023-10-13 07:32 UTC, asturur commented
I m actually trying to figure out which part was broken and then i can help you writing a test.

2023-10-13 08:41 UTC, asturur commented on src/util/misc/svgParsing.ts
> +      str += separator === ':' ? `${prop}-opacity: ${opacity.toString()}; ` : `${prop}-opacity="${opacity.toString()}" `;
the code is fine as it is, and i not holding an approval on this.
But you you want to step up the game of cleaning up, you can remove at least 2 ternaries with something like this:

```ts
let colorValue;
let opacityValue;
if (!value) { 
  colorValue = 'none';
} else if(...) {
  colorValue = `#SVGID_${value.id}`;
} else {
 ....
 do color value and opacity value;
}
if (separator === ':') {
  return `${prop}: ${colorValue} ${opacityValue ? `${prop}-opacity: ${opacity.toString()}; ` : ''}`
} else {
 return `${prop}="${color.toRgb()}" ${opacityValue ? `${prop}-opacity="${opacity.toString()}" ` : ''}`
}

```

this maybe is easier to read? just a suggestion follow your gut feeling is not a big deal

2023-10-13 08:50 UTC, asturur commented
for the test, create a file

src/shapes/Text/TextSVGExportMixin.spec.ts

and inside test an svg export with background color:

```ts
describe('TextSvgExport', () => {
  it('exports text background color correctly', () => {
    const myText = new Text('This is a test', { backgroundColor: 'rgba(100, 0, 100, 0.5)' });
    const svgString = myText.toSVG();
    expect(svgString).toInclude('fill=....') // find the correct string
    expect(svgString).not.toInclude('fill: ....') // find the other string
  })
});

```

in case .toInclude is not an expect matcher, just use expect(svgString.includes(...string)).toBe(true) and toBe(false)

Repeat the same test with different color to test 'none' and the other cases with a gradient i suppose.

2023-10-13 08:53 UTC, asturur commented
i also argue if seaparator is a good variable name.
Is kind of indirect, because the separator is the ':' for styles and '=' for attributes, but what change is not just the separator but the quotes too.
A non expert dev could say, ok the function support a separator i can add a different one, while what the function does is just  forInlineStyle true/false or forAttributes false/true. Probably a boolean is nicer than the separator string.

Not an holding issue for me, just thought it could be pointed out

2023-10-13 09:02 UTC, tyutjohn commented
> i also argue if seaparator is a good variable name. Is kind of indirect, because the separator is the ':' for styles and '=' for attributes, but what change is not just the separator but the quotes too. A non expert dev could say, ok the function support a separator i can add a different one, while what the function does is just forInlineStyle true/false or forAttributes false/true. Probably a boolean is nicer than the separator string.
> 
> Not an holding issue for me, just thought it could be pointed out

I completely agree with you, I will improve it and add a new test file to complete the testing of the function, thanks for you help

2023-10-13 09:56 UTC, tyutjohn commented
> > i also argue if seaparator is a good variable name. Is kind of indirect, because the separator is the ':' for styles and '=' for attributes, but what change is not just the separator but the quotes too. A non expert dev could say, ok the function support a separator i can add a different one, while what the function does is just forInlineStyle true/false or forAttributes false/true. Probably a boolean is nicer than the separator string.
> > Not an holding issue for me, just thought it could be pointed out
> 
> I completely agree with you, I will improve it and add a new test file to complete the testing of the function, thanks for you help

Work done, everything looks fine

2023-10-13 11:12 UTC, asturur commented
We also need a new line in the changelog.md file in the root folder, sorry i forgot to ask you that

2023-10-13 11:37 UTC, tyutjohn commented
> We also need a new line in the changelog.md file in the root folder, sorry i forgot to ask you that

Already added, please try again

2023-10-13 19:07 UTC, asturur approved these changes

2023-10-13 19:08 UTC, asturur commented
Since @ShaMan123 requested some changes, let's give him time to review, but i think this is great.
Thank your for your contribution

2023-10-16 12:51 UTC, ShaMan123 approved these changes
Good job guys

2023-10-16 12:55 UTC, merged